## Q1) Assign your Name to variable name and Age to variable age. Make a Python program that prints your name and age.

In [7]:
name="Goutham"
age=20

In [12]:
print("My name is "+name+" and i am "+str(age)+" years old")

My name is Goutham and i am 20 years old


## Q2)X="Datascience is used to extract meaningful insights." Split the string

In [15]:
X="Datascience is used to extract meaningful insights." 
text = X.split()
print(text)

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


## Q3) Make a function that gives multiplication of two numbers

In [17]:
def multiplication(a,b):
    p=a*b
    print("Multiplication of two numbers: ",p)

In [18]:
a=60
b=22
multiplication(a,b)

Multiplication of two numbers:  1320


## Q4) Create a Dictionary of 5 States with their capitals. also print the keys and values.

In [19]:
StateAndCap={
    "Tamil Nadu":"Chennai",
    "Andhra Pradesh":"Amaravati",
    "Uttar Pradesh":"Lucknow",
    "Karnataka":"Bengaluru",
    "Kerala":"Thiruvananthapuram"
}

In [20]:
print(StateAndCap)

{'Tamil Nadu': 'Chennai', 'Andhra Pradesh': 'Amaravati', 'Uttar Pradesh': 'Lucknow', 'Karnataka': 'Bengaluru', 'Kerala': 'Thiruvananthapuram'}


## Q5) Create a list of 1000 numbers using range function.

In [23]:
x = list(range(1000))
print(type(x))

<class 'list'>


## Q6) Create an identity matrix of dimension 4 by 4

In [24]:
import numpy as np
identity_matrix = np.identity(4, dtype="int")
print(identity_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## Q7) Create a 3x3 matrix with values ranging from 1 to 9

In [26]:
np.arange(1,10).reshape((3,3))    

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Q8) Create 2 similar dimensional array and perform sum on them.

In [28]:
arr = [[1, 2, 3], [4, 5, 6], [2, 1, 2]]
SUM=sum(map(sum,arr))
print ("Sum = ",SUM)

Sum =  26


## Q9) Generate the series of dates from 1st Feb, 2023 to 1st March, 2023 (both inclusive)

In [29]:
from datetime import date, timedelta

start_date = date(2023, 2, 1) 
end_date = date(2023, 3, 1)   

delta = end_date - start_date   \

for i in range(delta.days + 1):
    day = start_date + timedelta(days=i)
    print(day)

2023-02-01
2023-02-02
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10
2023-02-11
2023-02-12
2023-02-13
2023-02-14
2023-02-15
2023-02-16
2023-02-17
2023-02-18
2023-02-19
2023-02-20
2023-02-21
2023-02-22
2023-02-23
2023-02-24
2023-02-25
2023-02-26
2023-02-27
2023-02-28
2023-03-01


## Q10) Given a dictionary, convert it into corresponding dataframe and display it dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}

In [31]:
import pandas as pd
dictionary = {'Brand': ['Maruti', 'Renault', 'Hyndai'], 'Sales' : [250, 200, 240]}
df=pd.DataFrame.from_dict(dictionary)
df

Brand  Sales
0   Maruti    250
1  Renault    200
2   Hyndai    240